In [1]:
import pandas

In [2]:
db=pandas.read_csv('salary_prediction.csv')

In [4]:
db.columns


Index(['YearsExperience', 'Salary'], dtype='object')

In [5]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes


In [6]:
y=db['Salary']

In [20]:
x=db['YearsExperience']

In [23]:
x=x.values.reshape(-1,1)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
model=LinearRegression()

In [26]:
model.fit(x ,y)

LinearRegression()

In [27]:
model.coef_

array([9449.96232146])

In [28]:
model.predict([[2.5]])

array([49417.10600231])

In [30]:
9449.96232146*2.5

23624.90580365

In [32]:
c=model.intercept_

25792.20019866871

In [34]:
c+9449.96232146*2.5

49417.10600231871

In [35]:
model.predict([[1.1]])

array([36187.15875227])

In [37]:
model.predict([[1.1]])

91.97864614358335

In [38]:
import joblib

In [39]:
joblib.dump(model,"sal.pk1")

['sal.pk1']